CREATE DATABASE quizzer;

CREATE TABLE `quizzer`.`quizzes` (
    `NAME` VARCHAR(100) NOT NULL,
    `QUESTIONS` JSON NOT NULL,
    `ANSWERS` JSON NOT NULL,
    `MAX_SCORE` INT NOT NULL,
    UNIQUE (NAME),
    PRIMARY KEY (NAME)
);

CREATE TABLE `quizzer`.`results` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `UID` VARCHAR(100) NOT NULL,
    `QUIZ` VARCHAR(100) NOT NULL,
    `ANSWERS` JSON NOT NULL,
    `SCORE` INT NOT NULL,
    UNIQUE (ID),
    UNIQUE (UID),
    PRIMARY KEY (UID),
    FOREIGN KEY (QUIZ) REFERENCES `quizzes`(NAME)
);

